# Generated by Django 5.2.1 on 2025-05-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date'], 'permissions': [('can_create_comment', 'Can create comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-pub_date'], 'permissions': [('can_publish', 'Can publish posts'), ('can_unpublish', 'Can unpublish posts')]},
        ),
    ]
