# Generated by Django 5.2.1 on 2025-05-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_comment_options_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_date'], 'permissions': [('can_create_comment', 'Can create comment'), ('can_edit_comment', 'Can edit comment'), ('can_delete_comment', 'Can delete comment')]},
        ),
    ]
